version: "3.8"
services:
  frontend:
    build:
      context: ./wiki-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build:
      context: ./wiki-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
